<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace wenbinye\tars\stat;

use wenbinye\tars\protocol\annotation\TarsClient;
use wenbinye\tars\protocol\annotation\TarsParameter;
use wenbinye\tars\protocol\annotation\TarsReturnType;

/**
 * @TarsClient(name="tars.tarsproperty.PropertyObj")
 */
interface PropertyFServant
{
    /**
     * @TarsParameter(name = "statmsg", type = "map<StatPropMsgHead, StatPropMsgBody>")
     * @TarsReturnType(type = "int")
     *
     * @param \wenbinye\tars\protocol\type\StructMap $statmsg
     *
     * @return int
     */
    public function reportPropMsg($statmsg);
}
