<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace wenbinye\tars\stat;

use wenbinye\tars\protocol\annotation\TarsClient;
use wenbinye\tars\protocol\annotation\TarsParameter;
use wenbinye\tars\protocol\annotation\TarsReturnType;

/**
 * @TarsClient(name="tars.tarsnode.ServerObj")
 */
interface ServerFServant
{
    /**
     * @TarsParameter(name = "serverInfo", type = "ServerInfo")
     * @TarsReturnType(type = "int")
     *
     * @param \wenbinye\tars\stat\ServerInfo $serverInfo
     *
     * @return int
     */
    public function keepAlive($serverInfo);

    /**
     * @TarsParameter(name = "app", type = "string")
     * @TarsParameter(name = "serverName", type = "string")
     * @TarsParameter(name = "version", type = "string")
     * @TarsReturnType(type = "int")
     *
     * @param string $app
     * @param string $serverName
     * @param string $version
     *
     * @return int
     */
    public function reportVersion($app, $serverName, $version);
}
