<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0
 */

namespace wenbinye\tars\rpc\fixtures\test;

use wenbinye\tars\protocol\annotation\TarsClient;
use wenbinye\tars\protocol\annotation\TarsReturnType;

/**
 * @TarsClient(name="UserObj")
 */
interface UserServant
{
    /**
     * @TarsReturnType(type = "vector<User>")
     *
     * @return User[]
     */
    public function findAll(): array;
}
