<?php

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace wenbinye\tars\client;

use wenbinye\tars\protocol\annotation\TarsProperty;

final class GetConfigListInfo
{
    /**
     * @TarsProperty(order = 0, required = true, type = "string")
     * @var string
     */
    public $appname;

    /**
     * @TarsProperty(order = 1, required = false, type = "string")
     * @var string
     */
    public $servername;

    /**
     * @TarsProperty(order = 2, required = false, type = "bool")
     * @var bool
     */
    public $bAppOnly = false;

    /**
     * @TarsProperty(order = 3, required = false, type = "string")
     * @var string
     */
    public $host = "";

    /**
     * @TarsProperty(order = 4, required = false, type = "string")
     * @var string
     */
    public $setdivision = "";

    /**
     * @TarsProperty(order = 5, required = false, type = "string")
     * @var string
     */
    public $containername = "";

}
