<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0
 */

namespace wenbinye\tars\client;

use wenbinye\tars\protocol\annotation\TarsClient;
use wenbinye\tars\protocol\annotation\TarsParameter;
use wenbinye\tars\protocol\annotation\TarsReturnType;

/**
 * @TarsClient(name="tars.tarslog.LogObj")
 */
interface LogServant
{
    /**
     * 记录远程日志.
     *
     * @tars-param app, 应用名称
     * @tars-param server, 服务名称
     * @tars-param file, 文件名称
     * @tars-param format, 日志时间格式(%Y%m%d)
     * @tars-param buffer, 日志内容
     *
     * @TarsParameter(name = "app", type = "string")
     * @TarsParameter(name = "server", type = "string")
     * @TarsParameter(name = "file", type = "string")
     * @TarsParameter(name = "format", type = "string")
     * @TarsParameter(name = "buffer", type = "vector<string>")
     * @TarsReturnType(type = "void")
     *
     * @param string   $app
     * @param string   $server
     * @param string   $file
     * @param string   $format
     * @param string[] $buffer
     *
     * @return void
     */
    public function logger(string $app, string $server, string $file, string $format, array $buffer): void;

    /**
     * 记录远程日志.
     *
     * @tars-param info, LogInfo
     * @tars-param buffer, 日志内容
     *
     * @TarsParameter(name = "info", type = "LogInfo")
     * @TarsParameter(name = "buffer", type = "vector<string>")
     * @TarsReturnType(type = "void")
     *
     * @param LogInfo  $info
     * @param string[] $buffer
     *
     * @return void
     */
    public function loggerbyInfo(LogInfo $info, array $buffer): void;
}
