<?php

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace wenbinye\tars\client;

use wenbinye\tars\protocol\annotation\TarsProperty;

final class StatPropInfo
{
    /**
     * @TarsProperty(order = 0, required = true, type = "string")
     * @var string
     */
    public $policy;

    /**
     * @TarsProperty(order = 1, required = true, type = "string")
     * @var string
     */
    public $value;

}
