<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0
 */

namespace wenbinye\tars\client;

use wenbinye\tars\protocol\annotation\TarsProperty;

final class StatSampleMsg
{
    /**
     * @TarsProperty(order = 0, required = true, type = "string")
     *
     * @var string|null
     */
    public $unid;

    /**
     * @TarsProperty(order = 1, required = true, type = "string")
     *
     * @var string|null
     */
    public $masterName;

    /**
     * @TarsProperty(order = 2, required = true, type = "string")
     *
     * @var string|null
     */
    public $slaveName;

    /**
     * @TarsProperty(order = 3, required = true, type = "string")
     *
     * @var string|null
     */
    public $interfaceName;

    /**
     * @TarsProperty(order = 4, required = true, type = "string")
     *
     * @var string|null
     */
    public $masterIp;

    /**
     * @TarsProperty(order = 5, required = true, type = "string")
     *
     * @var string|null
     */
    public $slaveIp;

    /**
     * @TarsProperty(order = 6, required = true, type = "int")
     *
     * @var int|null
     */
    public $depth;

    /**
     * @TarsProperty(order = 7, required = true, type = "int")
     *
     * @var int|null
     */
    public $width;

    /**
     * @TarsProperty(order = 8, required = true, type = "int")
     *
     * @var int|null
     */
    public $parentWidth;
}
